apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      serviceAccountName: clo835
      containers:
      - name: flask
        image: 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipin/my_app:latest
        ports:
        - containerPort: 81
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: flask-storage
          mountPath: /app/data
      volumes:
      - name: flask-storage
        persistentVolumeClaim:
          claimName: flask-app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 81
